### ISSUE TITLE
Support for RPC version 16 (Transmission 3.0)

### ISSUE THREAD

**Issue by audebert** [hekmon/transmissionrpc#13]
Hi!

Transmission 3.0 was released with some changes in the RPC protocol. I could not find the exact list of changes, but it appears that some fields have changed types. For example `trackerStats` now uses `bool` for `lastAnnounceTimedOut`.

This breaks JSON unmarshal due to type mismatches:

```
'torrent-get' rpc method failed: can't unmarshall request answer body: json: cannot unmarshal bool into Go struct field torrentGetResults.arguments.torrents of type int64
```

Cheers,

**Comment by hekmon** [comment]
[This](https://github.com/transmission/transmission/blob/3.00/extras/rpc-spec.txt#L806) seems to be a good place to start ! To be even more specific, a [diff](https://github.com/transmission/transmission/compare/2.94...3.00#diff-00888abf98b1e4cf251988b3d772de61) between the specs should be the best.

However, from what you reported it seems not all changes have been transparently written to the spec file. If `lastAnnounceTimedOut` is indeed a proper bool now, [that kind](https://github.com/hekmon/transmissionrpc/blob/v1.1.0/torrent_accessors.go#L554) of thing is not necessary anymore.

I fear a lot of testing is needed just to fix the existing functionalities before even adding new ones (fortunately it seems there is not a lot of them). And to be 100% honest with you I won't be able to start working on this soon for personnal life reasons. However if you want to start the work on a branch of yours attached to a PR, I will gladly answer your questions if any :)

Hopefully this will yield a v2 of this lib with RPC v16 support !

**Comment by shric** [comment]
Just summarizing my observations of RPC v16 vs v15 here

#14 addresses these changes:

- `trackerStats` as mentioned above now uses a `bool` for `lastScrapeTimedOut`. Actually `lastAnnounceTimedOut` was already `bool`.
- `Labels` has been added to `torrent-get` and `torrent-set`.
- `editDate` has been added to `torrent-get`.

Not implemented:

- `format` request argument for `torrent-get`. This allows torrent data to be returned as an array of arrays instead of a json blob and provides little to no benefit to users of this package as the package already unmarshals the JSON for you.

- `fields` request argument for `session-get`. This is like `fields` in `torrent-get`. The ability to select only the desired fields for `torrent-get` provides an enormous speed increase which is especially apparent when dealing with many torrents. `session-get` is a much smaller payload whose time and size doesn't scale on the number of torrents so it also doesn't provide much benefit.

**Comment by hekmon** [comment]
Thanks to the work of @shric master should be compatible to RPC v16 while not being feature complete yet.

While work continue toward a full v2 of the lib, if you need RPC v16 compatibility for now I suggest to track master or 05b4d9c9659e4cc507f6d212e4c5de9e5d1445bc for more stability.

I will leave this issue open until v2 is complete.

**Comment by hekmon** [comment]
[v2](/hekmon/transmissionrpc/releases/tag/v2.0.0) has been released !
