### ISSUE TITLE
proposal: use  go-humanize package instead of cunits

### ISSUE THREAD

**Issue by notjedi** [hekmon/transmissionrpc#18]
the [go-humanize](https://github.com/dustin/go-humanize) package is already being used by more than [8k](https://github.com/dustin/go-humanize/network/dependents?package_id=UGFja2FnZS0yMjY0ODE0MDM0) packages. so i suggest that using that is more reasonable. as an added benefit, it also supports converting time (which can be used for the `eta` and `etaIdle` fields).

**Comment by hekmon** [comment]
Hello notjedi,

cunits is doing the job perfectly fine, I do not see a valid reason to switch (performance, security, ...) because the scope of this lib is relatively small (multiply and divides floats and some basic string formating).

But this project has been open to community input and if you truly think it would be a good change, I would be happy to review a merge request.

Just keep in mind that because it will change the API of the lib, a change like this would require a new major version in semver. So even if the change is merged into master, it won't be part of release just yet. You will still be able to target this specific commit in your mod file tu use it in your project if that is what you want while waiting for a hypothetic v3 to be released.

If you are interested in creating a MR for this issue, I will leave it open until merge. Else, if it was simply a suggestion, I thank you for your input but will close it as I am perfectly ok with cunits.

Cheers

**Comment by notjedi** [comment]
hi @hekmon. sorry i did not go through the documentation thoroughly when i opened this issue. i was thinking about closing this issue while i was reading the go reference for `cuints` yesterday but just forgot to do it later on. `cuints` is perfectly fine.
