### ISSUE TITLE
Execute torrent actions over Torrent struct (i.e. torrent.RenamePath())

### ISSUE THREAD

**Issue by elboletaire** [hekmon/transmissionrpc#6]
I've been trying this on my own ~~with no luck~~*, let's see what do you think about it.

The idea is to be able to run some actions, like `TorrentRenamePath` or `TorrentSetLocation`, directly from the torrent object, so, instead of doing this:

```go
ids := []string{"7C03A705D4BBF4F74A97401FD0165CC4D7E7DDD4"}
fields := []string{"id", "files", "hashString"}
torrents, err := client.TorrentGetHashes(fields, ids)

if err != nil {
  panic(err)
}

err = client.TorrentRenamePath(*torrents[0].ID, "FileName.mkv", "NewFileName.mkv")

if err != nil {
  panic(err)
}
```

Be able to do this:

```go
ids := []string{"7C03A705D4BBF4F74A97401FD0165CC4D7E7DDD4"}
fields := []string{"id", "files", "hashString"}
torrents, err := client.TorrentGetHashes(fields, ids)

if err != nil {
  panic(err)
}

err = torrent[0].RenamePath("FileName.mkv", "NewFileName.mkv")

if err != nil {
  panic(err)
}
```

As said, I've tried this on my own.. but I started coding golang just three days ago and obviously my skills are still far from good.

Couldn't think in a way to use the `Client` inside a `Torrent` function, so I decided to try binding the Client to every Torrent to be able to access it later inside the function (again, I'm a newbie :)):

First I added the `Client` property to the `Torrent` struct:

```go
type Torrent struct {
  // Original code below
  Client  *Client
}
```

Then I defined a new `Torrents` type for the `[] *Torrent` type with a `BindClient` to bind the client to every torrent:

```go
type Torrents []*Torrent

func (t Torrents) BindClient(client *Client) {
  for _, torrent := range t {
    torrent.BindClient(client)
  }
}

// And a BindClient method for the Torrent:
func (t *Torrent) BindClient(client *Client) {
  t.Client = client
}
```

Obviously, after adding that `Torrents` type, I've searched-and-replaced all the `[]*Torrent` matches in the code with `Torrents`.

Finally, in the `torrentGet` and `torrentGetHash` methods I bind the client to every torrent:

```go
func (c *Client) torrentGet(fields []string, ids []int64) (torrents Torrents, err error) {
  // Original code below
  torrents = result.Torrents
  // Addition
  torrents.BindClient(c)
  return
}

func (c *Client) torrentGetHash(fields []string, ids []string) (torrents Torrents, err error) {
  // Original code below
  torrents = result.Torrents
  // Addition
  torrents.BindClient(c)
  return
}
```

And the `RenamePath` method looks like this:

```go
// RenamePath directly from torrent
func (t *Torrent) RenamePath(path, name string) (err error) {
  return t.Client.TorrentRenamePath(*t.ID, path, name)
}
```

Doing this it works.... but I'm not really sure this is the best way. I think it would be better if can be done during the unmarshalling, but couldn't find a way to do it.

Edit: I neither like binding the client to every torrent, maybe there's a better way (?)

Please, let me know your thoughts :smiley: 

\* Edit2: I started creating the issue saying "with no luck" because at the very start of writing it I had a syntax error on my code which was making it fail, but it works as said later.

**Comment by hekmon** [comment]
I never liked to attach controller directly to "final" data (could have exceptions wih sub parts where un controller yields a smaller controller only to work on a sub field with a restricted perimeter). I always preferred the OOP/MVC approach, it allows me to think more efficiently. Controllers do hold data, but only for connection state or config and their main roles are to abstract interactions with another components. What they return are "dead" data for me, in a sense that this data has to be agnostic and standard as much as possible because it can/could be passed to other controllers. Even if I understand the goal (torrent.Rename() which can have sense for a human reading) on my side a torrent struct does not known how to act: it is merely a container of data/metadata (passive object). Only controllers are active objects specialized on acting on data. Attaching a controller to a torrent data would break this organization/coding style to produce a code I am not comfortable with. So unfortunately that kind of modifications will never go into the lib.

This leave you with two solutions:
* forking the lib (and make extra work to implements back original lib updates within yours)
* create a wrapping layer with golang inheritance (easy to keep yourself updated even if the lib receives updates)

Here is some pseudo code:
```go
type activeTorrent struct {
    *transmissionrpc.Torrent
    *transmissionrpc.Client
}

func GetTorrentHash(hash string) (at *activeTorrent, err error) {
    // make the lib call
    torrent, err := client.TorrentGetAllForHashes([]string{hash})
    if err != nil {
        return
    }
    // todo: test len(torrent) == 1
    // return your object
    at = &activeTorrent{
        Client: client,
        Torrent: torrent,
    }
    return
}

func (at *activeTorrent) RenamePath(path, name string) (err error) {
     return at.Client.TorrentRenamePath(*at.Torrent.ID, path, name)
}
``` 

Which is kinda what you did, but on another package :) Remember that I am not a big fan of this solution so if you want to modify the lib directly, you will have to maintain a fork. I think this solution of a wrapping layer is better because you can still rely on the lib (even on the future) while building an interaction layer you are comfortable with.

**Comment by elboletaire** [comment]
Thank you! It totally makes sense, and that’s why I wanted to ask before doing a PR which would had end in nothing.

After what you said, I supose you won’t consider making a Torrent controller and use it instead than the current Torrent struct? The current one could be returned using a Data() method or similar.

**Comment by hekmon** [comment]
I'm afraid not :)

But I understand why/the logic behind your thinking ! tastes and colours I guess ;)

**Comment by elboletaire** [comment]
Ok no problem! :)
